linters:
  enable:
    - dogsled
    - dupword
    - dupl
    - govet
    - gofmt
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - gocognit
