name: Go CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - name: Install dependencies
        run: go install
        working-directory: ${{ env.relativePath }}
      - name: Build SDK project
        run: go build
        working-directory: ${{ env.relativePath }}
      - name: Run unit tests
        run: go test -v
        working-directory: ./
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest