name: Create Weekly Preview Release

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight (UTC)
  workflow_dispatch: # Manual trigger

env:
  PREVIEW_VERSION:

jobs:
  create_preview_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Version
        id: read_version
        run: |
          unreleased_version=$(cat VERSION)
          echo "PREVIEW_VERSION=$unreleased_version-preview$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{env.PREVIEW_VERSION}}"
          message: "Preview Release $PREVIEW_VERSION"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: anton-yurchenko/git-release@v5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "true"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
